name: Pulumi
on:
  #pull_request:
  #  type: [opened]
  #  branches: [main]
  push:

jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: organization/try-pulumi-civo/dev
          cloud-url: "s3://pulumi-state-91536e4?endpoint=objectstore.lon1.civo.com&disableSSL=true&s3ForcePathStyle=true"
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

